import { createSlice } from '@reduxjs/toolkit';

import { CategoryType } from '~/types/recipeType';

const initialState: CategoryType[] = [
    {
        id: 'salads',
        name: 'Салаты',
        nameEn: 'salads',
        icon: 'salads',
        subcategories: [
            { id: 'meat-salads', name: 'Мясные салаты', nameEn: 'meat-salads' },
            { id: 'fish-salads', name: 'Рыбные салаты', nameEn: 'fish-salads' },
            { id: 'vegetable-salads', name: 'Овощные салаты', nameEn: 'vegetable-salads' },
            { id: 'warm-salads', name: 'Теплые салаты', nameEn: 'warm-salads' },
        ],
        description: 'Полезные и оригинальные салаты на все случаи',
    },
    {
        id: 'snacks',
        name: 'Закуски',
        nameEn: 'snacks',
        icon: 'snacks',
        subcategories: [
            { id: 'meat-snacks', name: 'Мясные закуски', nameEn: 'meat-snacks' },
            { id: 'fish-snacks', name: 'Рыбные закуски', nameEn: 'fish-snacks' },
            { id: 'vegetable-snacks', name: 'Овощные закуски', nameEn: 'vegetable-snacks' },
            { id: 'warm-snacks', name: 'Теплые закуски', nameEn: 'warm-snacks' },
            { id: 'sandwiches', name: 'Бутерброды', nameEn: 'sandwiches' },
            { id: 'fast-food', name: 'Фастфуд', nameEn: 'fast-food' },
        ],
        description: 'Быстрые и вкусные закуски к любому столу',
    },
    {
        id: 'first-dish',
        name: 'Первые блюда',
        nameEn: 'first-dish',
        icon: 'firstCourses',
        subcategories: [
            { id: 'meat-soups', name: 'Мясные супы', nameEn: 'meat-soups' },
            { id: 'vegetable-soups', name: 'Овощные супы', nameEn: 'vegetable-soups' },
            { id: 'broths', name: 'Бульоны', nameEn: 'broths' },
            { id: 'cold-soups', name: 'Холодные супы', nameEn: 'cold-soups' },
            { id: 'dietary-soups', name: 'Диетические супы', nameEn: 'dietary-soups' },
        ],
        description: 'Ароматные супы и бульоны на каждый день',
    },
    {
        id: 'second-dish',
        name: 'Вторые блюда',
        nameEn: 'second-dish',
        icon: 'secondCourses',
        subcategories: [
            { id: 'meat', name: 'Мясные', nameEn: 'meat' },
            { id: 'fish', name: 'Рыбные', nameEn: 'fish' },
            { id: 'vegetables', name: 'Овощные', nameEn: 'vegetables' },
            { id: 'poultry-dish', name: 'Из птицы', nameEn: 'poultry-dish' },
            { id: 'mushrooms', name: 'Из грибов', nameEn: 'mushrooms' },
            { id: 'offal', name: 'Из субпродуктов', nameEn: 'offal' },
            { id: 'steamed', name: 'На пару', nameEn: 'steamed' },
            { id: 'dumplings', name: 'Пельмени, вареники', nameEn: 'dumplings' },
            { id: 'flour-side', name: 'Мучные гарниры', nameEn: 'flour-side' },
            { id: 'vegetable-side', name: 'Овощные гарниры', nameEn: 'vegetable-side' },
            { id: 'pizza', name: 'Пицца', nameEn: 'pizza' },
            { id: 'sushi', name: 'Суши', nameEn: 'sushi' },
        ],
        description: 'Разнообразие вторых блюд на любой вкус',
    },
    {
        id: 'desserts',
        name: 'Десерты и выпечка',
        nameEn: 'desserts',
        icon: 'desserts',
        subcategories: [
            { id: 'pancakes', name: 'Блины и оладьи', nameEn: 'pancakes' },
            { id: 'pies', name: 'Пироги и пончики', nameEn: 'pies' },
            { id: 'cakes', name: 'Торты', nameEn: 'cakes' },
            { id: 'rolls', name: 'Рулеты', nameEn: 'rolls' },
            { id: 'muffins', name: 'Кексы и мафины', nameEn: 'muffins' },
            { id: 'cheesecakes', name: 'Сырники и ватрушки', nameEn: 'cheesecakes' },
            { id: 'puff-pastry', name: 'Из слоеного теста', nameEn: 'puff-pastry' },
            { id: 'custard-dough', name: 'Из заварного теста', nameEn: 'custard-dough' },
            { id: 'yeast-dough', name: 'Из дрожжевого теста', nameEn: 'yeast-dough' },
            { id: 'buns', name: 'Булочки и сдоба', nameEn: 'buns' },
            { id: 'bread', name: 'Хлеб', nameEn: 'bread' },
            { id: 'pizza-dough', name: 'Тесто на пиццу', nameEn: 'pizza-dough' },
            { id: 'creams', name: 'Кремы', nameEn: 'creams' },
        ],
        description: 'Сладкие десерты и домашняя выпечка',
    },
    {
        id: 'grills',
        name: 'Блюда на гриле',
        nameEn: 'grills',
        icon: 'grills',
        subcategories: [
            { id: 'beef', name: 'Говядина', nameEn: 'beef' },
            { id: 'pork', name: 'Свинина', nameEn: 'pork' },
            { id: 'poultry-grill', name: 'Птица', nameEn: 'poultry-grill' },
            { id: 'fish-grill', name: 'Рыба', nameEn: 'fish-grill' },
            { id: 'mushrooms-grill', name: 'Грибы', nameEn: 'mushrooms-grill' },
            { id: 'vegetables-grill', name: 'Овощи', nameEn: 'vegetables-grill' },
        ],
        description: 'Ароматные блюда с дымком и хрустящей корочкой',
    },
    {
        id: 'vegan',
        name: 'Веганская кухня',
        nameEn: 'vegan',
        icon: 'vegan',
        subcategories: [
            { id: 'snacks', name: 'Закуски', nameEn: 'snacks' },
            { id: 'first-dish', name: 'Первые блюда', nameEn: 'first-dish' },
            { id: 'second-dish', name: 'Вторые блюда', nameEn: 'second-dish' },
            { id: 'side-dishes', name: 'Гарниры', nameEn: 'side-dishes' },
            { id: 'desserts', name: 'Десерты', nameEn: 'desserts' },
            { id: 'baking', name: 'Выпечка', nameEn: 'baking' },
            { id: 'raw-food', name: 'Сыроедческие блюда', nameEn: 'raw-food' },
            { id: 'drinks', name: 'Напитки', nameEn: 'drinks' },
        ],
        description:
            'Интересны не только убеждённым вегетарианцам, но и тем, кто хочет попробовать вегетарианскую диету и готовить вкусные вегетарианские блюда.',
    },
    {
        id: 'kids-dish',
        name: 'Детские блюда',
        nameEn: 'kids-dish',
        icon: 'kidsCourses',
        subcategories: [
            { id: 'first-dish', name: 'Первые блюда', nameEn: 'first-dish' },
            { id: 'second-dish', name: 'Вторые блюда', nameEn: 'second-dish' },
            { id: 'side-dishes', name: 'Гарниры', nameEn: 'side-dishes' },
            { id: 'baking', name: 'Выпечка', nameEn: 'baking-kds' },
            { id: 'gluten-free', name: 'Без глютена', nameEn: 'gluten-free' },
            { id: 'sugar-free', name: 'Без сахара', nameEn: 'sugar-free' },
            { id: 'allergen-free', name: 'Без аллергенов', nameEn: 'allergen-free' },
            { id: 'baby-food', name: 'Блюда для прикорма', nameEn: 'baby-food' },
        ],
        description: 'Полезные и вкусные блюда для маленьких гурманов',
    },
    {
        id: 'therapeutic-nutrition',
        name: 'Лечебное питание',
        nameEn: 'therapeutic-nutrition',
        icon: 'therapeuticNutrition',
        subcategories: [
            { id: 'children-diet', name: 'Детская диета', nameEn: 'children-diet' },
            { id: 'diet-1', name: 'Диета №1', nameEn: 'diet-1' },
            { id: 'diet-2', name: 'Диета №2', nameEn: 'diet-2' },
            { id: 'diet-3', name: 'Диета №3', nameEn: 'diet-3' },
            { id: 'diet-4', name: 'Диета №4', nameEn: 'diet-4' },
            { id: 'diet-5', name: 'Диета №5', nameEn: 'diet-5' },
            { id: 'diet-6', name: 'Диета №6', nameEn: 'diet-6' },
            { id: 'diet-7', name: 'Диета №7', nameEn: 'diet-7' },
            { id: 'diet-8', name: 'Диета №8', nameEn: 'diet-8' },
            { id: 'diet-9', name: 'Диета №9', nameEn: 'diet-9' },
            { id: 'diet-10', name: 'Диета №10', nameEn: 'diet-10' },
            { id: 'diet-12', name: 'Диета №12', nameEn: 'diet-12' },
            { id: 'diet-13', name: 'Диета №13', nameEn: 'diet-13' },
            { id: 'diet-14', name: 'Диета №14', nameEn: 'diet-14' },
            { id: 'gluten-free-diet', name: 'Без глютена', nameEn: 'gluten-free-diet' },
            { id: 'allergen-free-diet', name: 'Без аллергенов', nameEn: 'allergen-free-diet' },
        ],
        description: 'Специальные диеты для поддержания здоровья',
    },
    {
        id: 'national',
        name: 'Национальные',
        nameEn: 'national',
        icon: 'national',
        subcategories: [
            { id: 'american', name: 'Американская кухня', nameEn: 'american' },
            { id: 'armenian', name: 'Армянская кухня', nameEn: 'armenian' },
            { id: 'greek', name: 'Греческая кухня', nameEn: 'greek' },
            { id: 'georgian', name: 'Грузинская кухня', nameEn: 'georgian' },
            { id: 'italian', name: 'Итальянская кухня', nameEn: 'italian' },
            { id: 'spanish', name: 'Испанская кухня', nameEn: 'spanish' },
            { id: 'chinese', name: 'Китайская кухня', nameEn: 'chinese' },
            { id: 'mexican', name: 'Мексиканская кухня', nameEn: 'mexican' },
            { id: 'pan-asian', name: 'Паназиатская кухня', nameEn: 'pan-asian' },
            { id: 'russian', name: 'Русская кухня', nameEn: 'russian' },
            { id: 'turkish', name: 'Турецкая кухня', nameEn: 'turkish' },
            { id: 'french', name: 'Французская кухня', nameEn: 'french' },
            { id: 'swedish', name: 'Шведская кухня', nameEn: 'swedish' },
            { id: 'japanese', name: 'Японская кухня', nameEn: 'japanese' },
            { id: 'other', name: 'Другая кухня', nameEn: 'other' },
        ],
        description: 'Кулинарные традиции разных стран мира',
    },
    {
        id: 'sauces',
        name: 'Соусы',
        nameEn: 'sauces',
        icon: 'sauces',
        subcategories: [
            { id: 'meat-sauces', name: 'Соусы мясные', nameEn: 'meat-sauces' },
            { id: 'cheese-sauces', name: 'Соусы сырные', nameEn: 'cheese-sauces' },
            { id: 'marinades', name: 'Маринады', nameEn: 'marinades' },
        ],
        description: 'Ароматные дополнения, преображающие любое блюдо',
    },
    {
        id: 'drinks',
        name: 'Напитки',
        nameEn: 'drinks',
        icon: 'drinks',
        subcategories: [
            { id: 'juices', name: 'Соки и фреши', nameEn: 'juices' },
            { id: 'smoothies', name: 'Смузи', nameEn: 'smoothies' },
            { id: 'compotes', name: 'Компоты', nameEn: 'compotes' },
            { id: 'kissels', name: 'Кисели', nameEn: 'kissels' },
            { id: 'coffee', name: 'Кофе', nameEn: 'coffee' },
            { id: 'medicinal-tea', name: 'Лечебный чай', nameEn: 'medicinal-tea' },
            { id: 'kvass', name: 'Квас', nameEn: 'kvass' },
            { id: 'cocktails', name: 'Коктейли', nameEn: 'cocktails' },
            { id: 'alcoholic', name: 'Алкогольные', nameEn: 'alcoholic' },
        ],
        description: 'Освежающие, согревающие и полезные напитки',
    },
    {
        id: 'preparations',
        name: 'Домашние заготовки',
        nameEn: 'preparations',
        icon: 'preparations',
        subcategories: [
            { id: 'meat-preparations', name: 'Мясные заготовки', nameEn: 'meat-preparations' },
            { id: 'fish-preparations', name: 'Рыбные заготовки', nameEn: 'fish-preparations' },
            { id: 'cucumbers', name: 'Из огурцов', nameEn: 'cucumbers' },
            { id: 'tomatoes', name: 'Из томатов', nameEn: 'tomatoes' },
            { id: 'mushrooms-preparations', name: 'Из грибов', nameEn: 'mushrooms-preparations' },
            {
                id: 'vegetable-preparations',
                name: 'Овощные заготовки',
                nameEn: 'vegetable-preparations',
            },
            { id: 'salads-preparations', name: 'Салаты, икра', nameEn: 'salads-preparations' },
            { id: 'fruits-berries', name: 'Из фруктов и ягод', nameEn: 'fruits-berries' },
        ],
        description: 'Заготовки на зиму и консервированные деликатесы',
    },
];

const categoriesSlice = createSlice({
    name: 'categories',
    initialState,
    reducers: {},
});

export const categoriesReducer = categoriesSlice.reducer;
