export const DATA_TEST_ID = {
    HEADER: 'header',
    FOOTER: 'footer',
    CAROUSEL: 'carousel',
    CAROUSEL_CARD: 'carousel-card-',
    CAROUSEL_BACK: 'carousel-back',
    CAROUSEL_FORWARD: 'carousel-forward',
    ACTIVE_LINK: '-active',
    JUICIEST_LINK: 'juiciest-link',
    JUICIEST_LINK_MOB: 'juiciest-link-mobile',
    CHECKBOX: 'checkbox-',
    FOOD_CARD: 'food-card-',
    BURGER_NAV: 'nav',
    BURGER_ICON: 'hamburger-icon',
    BURGER_CLOSE_ICON: 'close-icon',
    ALLERGENS_SWITCHER: 'allergens-switcher',
    ADD_OTHER_ALLERGEN: 'add-other-allergen',
    ADD_ALLERGEN_BUTTON: 'add-allergen-button',
    ALLERGENS_MENU: 'allergens-menu',
    ALLERGEN: 'allergen-',
    VEGAN: 'vegan',
    VEGAN_CUISINE: 'vegan-cuisine',
    BREADCRUMBS: 'breadcrumbs',
    LOAD_MORE_BUTTON: 'load-more-button',
    ERROR_PAGE_GO_HOME: 'error-page-go-home',
    CLOSE_FILTER_DRAWER: 'close-filter-drawer',
    ALLERGENS_SWITCHER_FILTER: 'allergens-switcher-filter',
    ALLERGENS_MENU_BUTTON: 'allergens-menu-button',
    ALLERGEN_MENU_BUTTON_FILTER: 'allergens-menu-button-filter',
    CLEAR_FILTER_BUTTON: 'clear-filter-button',
    FILTER_DRAWER: 'filter-drawer',
    FIND_RECIPE_BUTTON: 'find-recipe-button',
    INCREMENT_STEPPER: 'increment-stepper',
    DECREMENT_STEPPER: 'decrement-stepper',
    FILTER_TAG: 'filter-tag',
    SEARCH_BUTTON: 'search-button',
    SEARCH_INPUT: 'search-input',
    FILTER_BUTTON: 'filter-button',
    FILTER_MENU_BUTTON_CATEGORY: 'filter-menu-button-категория',
    ERROR_NOTIFICATION: 'error-notification',
    CLOSE_ALERT_BUTTON: 'close-alert-button',
    APP_LOADER: 'app-loader',
    LOADER_SEARCH_BLOCK: 'loader-search-block',
    FORM_SIGN_IN: 'sign-in-form',
    FORM_LOGIN_INPUT: 'login-input',
    FORM_PASSWORD_INPUT: 'password-input',
    FORM_PASSWORD_VISIBILITY: 'password-visibility-button',
    FORM_SUBMIT_BUTTON: 'submit-button',
    FORM_FORGOT_PASSWORD: 'forgot-password',
    MODAL_ERROR_SIGN_IN: 'sign-in-error-modal',
    MODAL_CLOSE_BUTTON: 'close-button',
    MODAL_REPEAT_BUTTON: 'repeat-button',
    SIGN_UP_PROGRESS: 'sign-up-progress',
    SIGN_UP_FORM: 'sign-up-form',
    SIGN_UP_FIRST_NAME: 'first-name-input',
    SIGN_UP_LAST_NAME: 'last-name-input',
    SIGN_UP_EMAIL: 'email-input',
    SIGN_UP_CONFIRM_PASSWORD: 'confirm-password-input',
    MODAL_SIGN_UP_SUCCESS: 'sign-up-success-modal',
    MODAL_SIGN_UP_ERROR: 'email-verification-failed-modal',
    MODAL_SEND_EMAIL: 'send-email-modal',
    MODAL_VERIFICATION_CODE: 'verification-code-modal',
    VERIFICATION_CODE_INPUT: 'verification-code-input',
    MODAL_RESET_CREDS: 'reset-credentials-modal',
    RECIPE_FORM: 'recipe-form',
    RECIPE_IMAGE_BLOCK: 'recipe-image-block',
    RECIPE_IMAGE_BLOCK_INPUT: 'recipe-image-block-input-file',
    RECIPE_CATEGORIES: 'recipe-categories',
    RECIPE_TITLE: 'recipe-title',
    RECIPE_DESCRIPTION: 'recipe-description',
    RECIPE_PORTIONS: 'recipe-portions',
    RECIPE_TIME: 'recipe-time',
    RECIPE_INGREDIENTS_TITLE: (index: number) => `recipe-ingredients-title-${index}`,
    RECIPE_INGREDIENTS_COUNT: (index: number) => `recipe-ingredients-count-${index}`,
    RECIPE_INGREDIENTS_MEASURE: (index: number) => `recipe-ingredients-measureUnit-${index}`,
    RECIPE_STEP_IMAGE: (index: number) => `recipe-steps-image-block-${index}`,
    RECIPE_STEP_IMAGE_INPUT: (index: number) => `recipe-steps-image-block-${index}-input-file`,
    RECIPE_STEP_DESCRIPTION: (index: number) => `recipe-steps-description-${index}`,
    RECIPE_SAVE_DRAFT: 'recipe-save-draft-button',
    RECIPE_PUBLISH: 'recipe-publish-recipe-button',
    RECIPE_REMOVE_INGREDIENT: (index: number) => `recipe-ingredients-remove-ingredients-${index}`,
    RECIPE_ADD_INGREDIENT: 'recipe-ingredients-add-ingredients',
    RECIPE_STEP_IMAGE_BLOCK: (index: number) => `recipe-steps-image-block-${index}-preview-image`,
    RECIPE_STEP_REMOVE: (index: number) => `recipe-steps-remove-button-${index}`,
    RECIPE_PREVIEW_IMAGE: 'recipe-image-block-preview-image',
    RECIPE_IMAGE_MODAL: 'recipe-image-modal',
    RECIPE_IMAGE_MODAL_BLOCK: 'recipe-image-modal-image-block',
    RECIPE_IMAGE_MODAL_PREVIEW: 'recipe-image-modal-preview-image',
    RECIPE_PREVENTIVE_MODAL: 'recipe-preventive-modal',
    RECIPE_DELETE_BUTTON: 'recipe-delete-button',
    HEADER_LOGO: 'header-logo',
    ADD_RECIPE_BTN: 'add-recipe-button',
};
